In [19]:
import torch
import numpy as np
import os
import cv2
from tqdm import tqdm
import glob

class Predictor:
    def __init__(self, imgs, modelPath='data/yoloModels/bestest.pt'):
        self.imgs = imgs
        self.model = torch.hub.load('src/yolov5','custom', path=modelPath, source='local', _verbose=False)
        self.centers = []
        self.results = [] # [[[xmin, xmax, ymin, ymax, certainty, classID, className, [centerX, centerY]], ...], ...]
        self.getPredictions()


    def __str__(self):
        return f'{len(self.imgs)} images, {self.name}'

    def getPredictions(self):
        for i, img in enumerate(self.imgs):
            currResult = self.model(img).pandas().xyxy[0].to_numpy()
            self.model(img).save(labels=True, save_dir=f'{os.getcwd()}/data/yoloPredictions/right')
            self.results.append([])
            for j, res in enumerate(currResult):
                self.results[-1].append([])
                for k, val in enumerate(res):
                    self.results[-1][-1].append(val)
                
                center = self.getCenter(*self.results[-1][-1][:4])
                self.results[-1][-1].append(center)


    def getCenter(self, xmin, xmax, ymin, ymax):
        return np.array([(xmin + xmax)/2, (ymin + ymax)/2]).astype(int)


In [20]:
path = 'data/conveyorImages/right'
imgs = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.png')]
pred = Predictor(imgs=imgs)

KeyboardInterrupt: 

In [ ]:
pred.results

[[],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [[1015.5994262695312,
   262.6264343261719,
   1114.639404296875,
   350.0936584472656,
   0.6753984689712524,
   2,
   'box',
   array([639, 732])]],
 [[1007.8289184570312,
   268.38720703125,
   1112.22705078125,
   353.64715576171875,
   0.857030987739563,
   2,
   'box',
   array([638, 732])]],
 [[1002.7635498046875,
   268.8050231933594,
   1109.7286376953125,
   354.5138854980469,
   0.8664320111274719,
   2,
   'box',
   array([635, 732])]],
 [[998.369873046875,
   270.41259765625,
   1108.7001953125,
   355.35382080078125,
  

In [21]:
image_folder = 'data/yoloPredictions/right/*'
video_name = 'right_cam_predicted.avi'#save as .avi
#is changeable but maintain same h&w over all  frames
width=1280
height=720 
#this fourcc best compatible for avi
fourcc = cv2.VideoWriter_fourcc('M','J','P','G')
video=cv2.VideoWriter(video_name,fourcc, 60, (width,height))

for i in tqdm((sorted(glob.glob(image_folder)))):
     x=cv2.imread(i)
     video.write(x)

cv2.destroyAllWindows()
video.release()

100%|██████████| 285/285 [00:03<00:00, 81.87it/s]
