In [49]:
import torch
import numpy as np
import os

class Predictor:
    def __init__(self, imgs, modelPath='data/yoloModels/best.pt'):
        self.imgs = imgs
        self.model = torch.hub.load('ultralytics/yolov5','custom', path=modelPath, verbose=False)
        # self.centers = []
        self.results = []
        self.getPredictions()


    def __str__(self):
        return f'{len(self.imgs)} images, {self.name}'

    def getPredictions(self):
        for img in self.imgs:
            self.results.append(self.model(img).pandas().xyxy[0].to_numpy())
            
            xmin = self.results[-1][0][0]
            ymin = self.results[-1][0][1]
            xmax = self.results[-1][0][2]
            ymax = self.results[-1][0][3]
            center = self.getCenter(xmin, xmax, ymin, ymax)
            self.results[-1][0] = self.results[-1][0].tolist()
            self.results[-1][0].append(self.getCenter(xmin, xmax, ymin, ymax))
            # self.centers.append(center)

    def getCenter(self, xmin, xmax, ymin, ymax):
        return np.array([(xmin + xmax)/2, (ymin + ymax)/2]).astype(int)


In [50]:
path = 'data\conveyorImages'
imgs = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.png')]

# centers = []
# for img in imgs:
#     obj = Object(img)
#     centers.append(obj.center)

pred = Predictor(imgs=imgs)


YOLOv5  2022-4-27 torch 1.11.0+cpu CPU

Fusing layers... 
Model summary: 213 layers, 7012822 parameters, 0 gradients
Adding AutoShape... 


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
pred.results

[array([[856.2462158203125, 310.13323974609375, 998.8065185546875, 426.71905517578125, 0.9314594268798828, 0, 'box']], dtype=object),
 array([[732.5384521484375, 334.01318359375, 891.630859375, 474.98284912109375, 0.9456979632377625, 0, 'box']], dtype=object),
 array([[628.7694091796875, 357.84063720703125, 793.7801513671875, 512.0861206054688, 0.9429858922958374, 0, 'box']], dtype=object),
 array([[575.2089233398438, 368.7104187011719, 741.6259155273438, 529.5492553710938, 0.9529181122779846, 0, 'box']], dtype=object)]