In [40]:
import torch
import numpy as np
import os

class Predictor:
    def __init__(self, imgs, modelPath='data/yoloModels/bestest.pt'):
        self.imgs = imgs
        self.model = torch.hub.load('ultralytics/yolov5','custom', path=modelPath, verbose=False)
        self.centers = []
        self.results = [] # [[[xmin, xmax, ymin, ymax, certainty, classID, className, [centerX, centerY]], ...], ...]
        self.getPredictions()


    def __str__(self):
        return f'{len(self.imgs)} images, {self.name}'

    def getPredictions(self):
        for i, img in enumerate(self.imgs):
            currResult = self.model(img).pandas().xyxy[0].to_numpy()
            self.results.append([])
            for j, res in enumerate(currResult):
                self.results[-1].append([])
                for k, val in enumerate(res):
                    self.results[-1][-1].append(val)
                
                center = self.getCenter(*self.results[-1][-1][:4])
                self.results[-1][-1].append(center)


    def getCenter(self, xmin, xmax, ymin, ymax):
        return np.array([(xmin + xmax)/2, (ymin + ymax)/2]).astype(int)


In [41]:
path = 'data\conveyorImages'
imgs = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.png')]

pred = Predictor(imgs=imgs)

YOLOv5  2022-4-25 torch 1.11.0+cpu CPU

Fusing layers... 
Model summary: 213 layers, 7018216 parameters, 0 gradients, 15.8 GFLOPs
Adding AutoShape... 


In [48]:
pred.results

[[[862.3251342773438,
   306.85455322265625,
   992.7933959960938,
   424.99810791015625,
   0.8889967799186707,
   2,
   'box',
   array([584, 708])]],
 [[729.0773315429688,
   337.5199890136719,
   893.0615844726562,
   475.6775207519531,
   0.8982843160629272,
   2,
   'box',
   array([533, 684])]],
 [[627.5916748046875,
   353.595703125,
   794.3533935546875,
   515.156005859375,
   0.9190041422843933,
   2,
   'box',
   array([490, 654])]],
 [[574.2073974609375,
   362.5861511230469,
   740.1697998046875,
   533.08935546875,
   0.9150750041007996,
   2,
   'box',
   array([468, 636])]]]